apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: product-ns
spec:
  type: NodePort
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 80          # Port exposed inside the cluster
      targetPort: 4000  # Your Node.js app port inside the container
      nodePort: 30080   # External port exposed on EC2 nodes (between 30000–32767)
