apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: product-ns
spec:
  type: LoadBalancer
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
