apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-admin-binding
  namespace: product-ns
subjects:
- kind: User
  name: "arn:aws:iam::259768585242:user/malith-dev"  # Replace with your full IAM user ARN
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
